server:
  port: 7070
  servlet:
    context-path: /market-auth
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internet_shop
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: fnmlaskfnaljkfhnalkfbnalkjfnbaklfnaklfnalksnfasklfnalskfn
  lifetime: 360000000

