server:
  port: 8081
  servlet:
    context-path: /market-cart
integrations:
  core-service:
    url: http://localhost:8080/market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

